[package]
name = "serde_divatree"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"
slab_tree = "0.3.2"
thiserror = "1.0.24"

[dev-dependencies]
serde_derive = "1.0.126"
